name: Java CI with Maven

on:
  push:
    branches: "**"
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        type: choice
        options: 
          - time_test
          - correctness_test
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: time_test
        if: ${{ github.event.inputs.deployment_target == 'time_test' }}
        run: mvn test -Dtest=TestFunction test
        working-directory: src/test/java
      - name: correctness_test
        if: ${{ github.event.inputs.deployment_target == 'correctness_test' }}
        run: mvn test -Dtest=TestLoadFunction test
        working-directory: src/test/java
