  workflow_dispatch:
    inputs:
      deployment_target:
        description:  Choose target
        required: true
        default:
        type: choice
        options: 
          - time_test
          - correctness_test
          
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: time_test
      run: mvn test -Dtest=main.TestFunction
    - name: correctness_test
      run: mvn test -Dtest=main.TestLoadFunction
